import type { Metadata } from "next";
import localFont from "next/font/local";

import Popup from "@/components/popup";
import AnimatedCanvas from "@/components/animated-canvas";

import "./globals.css";

const monumentGrotesk = localFont({
  src: [
    {
      path: "../fonts/MonumentGrotesk-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/MonumentGrotesk-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/MonumentGrotesk-Medium.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-monument-grotesk",
});

export const metadata: Metadata = {
  title: "Flare is the blockchain for data",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={`${monumentGrotesk.variable}`}>
        {children}
        <Popup />
        <AnimatedCanvas />
      </body>
    </html>
  );
}
